---
# file: ansible-role-erlang-packages/tasks/compile-erlang_ls.yml

- name: ERLANG_LS | check if already installed
  stat:
    path: "{{ erlang_ls_install_dir }}/erlang_ls"
  register: erlang_ls_exists

- name: ERLANG_LS | get from git repository
  git: repo="{{ erlang_ls_repo_url }}"
       dest="{{ erlang_ls_tmp }}"
       version="{{ erlang_ls_version }}"
  when: not erlang_ls_exists.stat.exists
  register: erlang_ls_downloaded

- name: ERLANG_LS | make and install
  command: chdir="{{ erlang_ls_tmp }}" make install
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ otp_install_dir }}/bin:/usr/local/bin"
  when: erlang_ls_downloaded.changed
  register: erlang_ls_make

- name: ERLANG_LS | cleanup tmp
  file:
    path: "{{ erlang_ls_tmp }}"
    state: absent
  when: erlang_ls_make.changed

...
